# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: beat
builds:
  - id: "fielbeat"
    binary: filebeat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    main: ./filebeat/filebeat.go
  # -
  #   id: "auditbeat"
  #   env:
  #       - CGO_ENABLED=0
  #   binary: auditbeat
  #   goos:
  #       - linux
  #       - darwin
  #   goarch:
  #       - 386
  #       - amd64
  #   main: ./auditbeat/auditbeat.go
  - id: "heartbeat"
    env:
      - CGO_ENABLED=0
    binary: heartbeat
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    main: ./heartbeat/heartbeat.go
  - id: "journalbeat"
    env:
      - CGO_ENABLED=0
    binary: journalbeat
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    main: ./journalbeat/journalbeat.go
  - id: "metricbeat"
    env:
      - CGO_ENABLED=0
    binary: heartbeat
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    main: ./metricbeat/metricbeat.go
  - id: "packetbeat"
    env:
      - CGO_ENABLED=0
    binary: heartbeat
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    main: ./packetbeat/packetbeat.go
  - id: "winlogbeat"
    env:
      - CGO_ENABLED=0
    binary: winlogbeat
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    main: ./winlogbeat/winlogbeat.go

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'